module.exports = {
  USERS_LOGIN: "/users/login",
  USER_LOGIN_FAIL: "/users/login/fail",
  USERS_REGISTER: "/users/register",
  USERS_COOKIE: "/users/cookie",
  USER_ID: "/user/:id",
  USER: "/user",
  USERS: "/users",
  USER_TICKETS: "/tickets",
  GROUPS: "/groups",
  GROUP_IDS: "/groups/ids",
  USER_ADDRESSES: "/addresses",
  NEW_ADDRESS: "/new_address",
  ADDRESS: "/address/:id",
  JOIN_INFO: "/join/:groupId",
  CREATE_GROUP: "/group/create",
  CURRENCY: "/currency",
  GROUP_ID: "/group/",
  GROUP_OCCSLOTS: "/group/occSlots"
};
